name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for GitVersion
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
        
    - name: Display GitVersion outputs
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        
    - name: Restore dependencies
      run: dotnet restore UniqueIdGenerator.SourceGen/UniqueIdGenerator.SourceGen.csproj
      
    - name: Set version from tag if available
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Using version from tag: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Using version from GitVersion: ${{ steps.gitversion.outputs.semVer }}"
          echo "VERSION=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_OUTPUT
        fi
        
    - name: Build
      run: dotnet build UniqueIdGenerator.SourceGen/UniqueIdGenerator.SourceGen.csproj --configuration Release --no-restore /p:Version=${{ steps.version.outputs.VERSION }}
      
    - name: Test
      run: dotnet test UniqueIdGenerator.Tests/UniqueIdGenerator.Tests.csproj --configuration Release
      
    - name: Pack
      run: dotnet pack UniqueIdGenerator.SourceGen/UniqueIdGenerator.SourceGen.csproj --configuration Release --no-build --output nuget-packages /p:Version=${{ steps.version.outputs.VERSION }}
      
    - name: Upload NuGet packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: nuget-packages/*.nupkg
        
    - name: Verify NuGet package
      run: |
        echo "Verifying NuGet package..."
        echo "Package details:"
        ls -la nuget-packages/
        nuget_file=$(ls -1 nuget-packages/*.nupkg | head -1)
        echo "Found package: $nuget_file"
        unzip -l "$nuget_file" || echo "Package preview unavailable"
      continue-on-error: true
        
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "Publishing NuGet package with version ${{ steps.gitversion.outputs.semVer }}"
        packagePath=$(ls -1 nuget-packages/*.nupkg | head -1)
        echo "Publishing package: $packagePath"
        dotnet nuget push "$packagePath" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols --verbosity detailed
      continue-on-error: false
